# Generated by Django 6.1.1 on 2026-09-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('drug_class', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('pair_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('severity', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(max_length=255)),
                ('source_record_id', models.CharField(blank=True, default='', max_length=255)),
                ('kb_version', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='interactions.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='interactions.drug')),
            ],
            options={
                'db_table': 'drug_interactions',
            },
        ),
        migrations.CreateModel(
            name='DrugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('normalized_alias', models.CharField(db_index=True, max_length=255)),
                ('alias_type', models.CharField(default='generic', max_length=50)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='interactions.drug')),
            ],
            options={
                'db_table': 'drug_aliases',
                'constraints': [models.UniqueConstraint(fields=('drug', 'normalized_alias'), name='unique_drug_alias')],
            },
        ),
    ]
